name: CI for node app

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Install dependencies
         run: npm install

       - name: Run tests
         run:  cd test && npm install && npm test